architectury {
	platformSetupLoomIde()
	fabric()
}

base {
	archivesName = "nec_testmod"
}

version = "1.0.0"
group = "io.github.natanfudge"

dependencies {
	implementation libs.fabric.loader
	implementation libs.fabric.api
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": project.version
	}
}

tasks.withType(JavaCompile).configureEach {
	options.encoding = "UTF-8"
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(25)
	}
	withSourcesJar()
}
