plugins {
    alias libs.plugins.architectury.loom apply false
    alias libs.plugins.minotaur apply false
    alias libs.plugins.architectury.plugin
    alias libs.plugins.cursegradle
    id 'maven-publish'
}

architectury {
    minecraft = libs.versions.minecraft.get()
}



subprojects {
    apply plugin: 'dev.architectury.loom-no-remap'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'
    if (gradle.startParameter.taskNames.any { it.toLowerCase(Locale.ROOT).contains("publish") || it.toLowerCase(Locale.ROOT).contains("curseforge") || it.toLowerCase(Locale.ROOT).contains("modrinth") }) {
        apply plugin: "com.modrinth.minotaur"
        apply plugin: 'com.matthewprenger.cursegradle'
    }


    def modVersion = libs.versions.mod.version.get()
    def minecraftVersion = libs.versions.minecraft.get()
    def total_version = "$modVersion+$minecraftVersion"
    ext.total_version = total_version

    def cf = libs.versions.overrides.curseforge.get()
    def mr = libs.versions.overrides.modrinth.get()

    ext.curseforge_mc_version = cf == 'mc' ? minecraftVersion : cf
    ext.modrinth_mc_version = mr == 'mc' ? minecraftVersion : mr
    ext.release_type = libs.versions.release.type.get()

    version = ext.total_version
    group = rootProject.maven_group

    base {
        // Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
        archivesName = "$rootProject.archives_base_name-$project.name"
    }

    tasks.withType(Jar).configureEach { jarTask ->
        jarTask.metaClass.getArchivePath = { -> jarTask.archiveFile.get().asFile }
    }

    dependencies {
        minecraft libs.minecraft
    }

    java {
        toolchain {
            languageVersion.set(JavaLanguageVersion.of(25))
        }
        withSourcesJar()
    }

}
task publishAll {
    group = "upload"
    dependsOn("fabric:publishFabric")
    dependsOn("neoforge:publishForge")
}

//task addTestFabricMod(type: Copy) {
//    dependsOn project(":TestFabricMod").tasks.build
//    from "TestFabricMod/build/libs/nec_testmod-1.0.0.jar"
//    into "fabric/run/mods"
//}
//
//task addTestForgeMod(type: Copy) {
//    dependsOn project(":TestForgeMod").tasks.build
////   Copy dev jar because there is no support for automatic remapping
//    from "TestForgeMod/build/libs/nec_testmod-1.0.0-dev-shadow.jar"
//    into "forge/run/mods"
//}
//
//task addTestMods {
//    dependsOn addTestFabricMod, addTestForgeMod
//}
