plugins {
    alias(libs.plugins.architectury.loom) apply false
    alias(libs.plugins.minotaur) apply false
    alias(libs.plugins.curseforgegradle) apply false
    alias(libs.plugins.architectury.plugin)
    id 'maven-publish'
}

architectury {
    minecraft = libs.versions.minecraft.get()
}

def modVersion = libs.versions.mod.version.get()
def minecraftVersion = libs.versions.minecraft.get()
def minecraftDependency = libs.minecraft
def curseForgeMinecraftVersion = libs.versions.overrides.curseforge.get()
def modrinthMinecraftVersion = libs.versions.overrides.modrinth.get()
def releaseType = libs.versions.release.type.get()

subprojects {
    apply plugin: 'dev.architectury.loom-no-remap'
    apply plugin: 'architectury-plugin'
    apply plugin: 'maven-publish'
    if (gradle.startParameter.taskNames.any { it.toLowerCase(Locale.ROOT).contains("publish") || it.toLowerCase(Locale.ROOT).contains("curseforge") || it.toLowerCase(Locale.ROOT).contains("modrinth") }) {
        apply plugin: "com.modrinth.minotaur"
        apply plugin: 'net.darkhax.curseforgegradle'
    }


    def total_version = "$modVersion+$minecraftVersion"
    ext.total_version = total_version

    ext.curseforge_mc_version = curseForgeMinecraftVersion == 'mc' ? minecraftVersion : curseForgeMinecraftVersion
    ext.modrinth_mc_version = modrinthMinecraftVersion == 'mc' ? minecraftVersion : modrinthMinecraftVersion
    ext.release_type = releaseType

    version = ext.total_version
    group = rootProject.maven_group

    base {
        // Set up a suffixed format for the mod jar names, e.g. `example-fabric`.
        archivesName = "$rootProject.archives_base_name-$project.name"
    }

    dependencies {
        minecraft minecraftDependency
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(25)
        }
        withSourcesJar()
    }

}

tasks.register('publishAll') {
    group = "upload"
    dependsOn("fabric:publishFabric")
    dependsOn("neoforge:publishNeoForge")
}
