
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx4048M
# Not supported by architectury, see https://github.com/architectury/architectury-loom/issues/266
#org.gradle.configuration-cache=true
#org.gradle.configuration-cache.parallel=true


archives_base_name=notenoughcrashes
maven_group=fudge.notenoughcrashes
mod_name=Not Enough Crashes
