plugins {
    alias(libs.plugins.shadow)
}

architectury {
    platformSetupLoomIde()
    neoForge()
}

configurations {
    common {
        canBeResolved = true
        canBeConsumed = false
    }
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentNeoForge.extendsFrom common

    // Files in this configuration will be bundled into your mod using the Shadow plugin.
    // Don't use the `shadow` configuration from the plugin itself as it's meant for excluding files.
    shadowBundle {
        canBeResolved = true
        canBeConsumed = false
    }
}



repositories {
    maven {
        name = 'NeoForged'
        url = 'https://maven.neoforged.net/releases'
    }
}

dependencies {
    neoForge libs.neoforge
    implementation libs.mixinextras.neoforge
    include libs.mixinextras.neoforge

    common(project(':common')) { transitive = false }
    shadowBundle project(path: ':common', configuration: 'runtimeElements')
}

processResources {
    def resourceProperties = [
            version          : project.version,
            minecraft_version: libs.versions.minecraft.get(),
            neoforge_version : libs.versions.neoforge.get()
    ]
    inputs.properties resourceProperties

    filesMatching('META-INF/neoforge.mods.toml') {
        expand resourceProperties
    }
}

shadowJar {
    configurations = [project.configurations.shadowBundle]
    archiveClassifier = 'dev-shadow'
}

jar {
    from(project(':common').sourceSets.main.output)
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

def forge_release  = "release"

plugins.withId('net.darkhax.curseforgegradle') {
    tasks.register('publishCurseForge', net.darkhax.curseforgegradle.TaskPublishCurseForge) {
        group = 'upload'
        apiToken = providers.gradleProperty('curseforge_api_key')
                .orElse(providers.environmentVariable('CURSEFORGE_TOKEN'))
                .getOrElse('')

        def mainFile = upload(442354, tasks.named('jar'))
        mainFile.releaseType = forge_release
        mainFile.addModLoader('NeoForge')
        mainFile.addGameVersion(curseforge_mc_version)
        mainFile.addEnvironment('Client', 'Server')
        mainFile.changelogType = 'markdown'
        mainFile.changelog = rootProject.file('changelog.md')
        mainFile.displayName = "$mod_name $total_version NeoForge"
    }
}

plugins.withId("com.modrinth.minotaur") {
    modrinth {
        group = "upload"
        token = providers.gradleProperty('modrinth_api_key')
                .orElse(providers.environmentVariable('MODRINTH_TOKEN'))
        projectId = 'yM94ont6'
        versionNumber = total_version + "-neoforge" // Will fail if Modrinth has this version already
        versionName = "$mod_name $total_version NeoForge"
        uploadFile = jar
        gameVersions = [modrinth_mc_version]
        loaders = ["neoforge"]
        changelog = rootProject.file("changelog.md").text
        versionType = forge_release
    }
}


tasks.register('publishNeoForge') {
    group = "publishing"
    dependsOn("publishCurseForge", "modrinth")
}
