# Based on Consistency+ Actions Script

name: Build NotEnoughCrashes
on: [ pull_request, push ]

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
        os: [windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: 1 - Checkout repository
        uses: actions/checkout@v2
      - name: 2 - Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: 3 - Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: ${{ matrix.java }}
      - name: 4 - Build
        run: ./gradlew build
      - name: 5 - Capture & upload build artifacts
        if: ${{ runner.os == 'windows-latest' }}
        uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
